# FST

In [1]:
def main():
    n = int(input())
    cur_num = 2
    if n == 0:
        print(0)
        return
    fst, snd = 0, 1
    while cur_num <= n:
        fst, snd = snd, fst + snd
        cur_num += 1
    print(snd)

main()

5
5


# SND

In [19]:
def main():
    n = int(input())
    for i in range(n):
        cur_word = raw_input()
        to_print = []
        for j in range(1, len(cur_word) + 1):
            for k in range(len(cur_word) - j + 1):
                to_print.append(cur_word[k:k + j])
        print(' '.join(to_print))
        
main()

7
shad
s h a d sh ha ad sha had shad
python_hw
p y t h o n _ h w py yt th ho on n_ _h hw pyt yth tho hon on_ n_h _hw pyth ytho thon hon_ on_h n_hw pytho ython thon_ hon_h on_hw python ython_ thon_h hon_hw python_ ython_h thon_hw python_h ython_hw python_hw
is_easy
i s _ e a s y is s_ _e ea as sy is_ s_e _ea eas asy is_e s_ea _eas easy is_ea s_eas _easy is_eas s_easy is_easy
next_empty
n e x t _ e m p t y ne ex xt t_ _e em mp pt ty nex ext xt_ t_e _em emp mpt pty next ext_ xt_e t_em _emp empt mpty next_ ext_e xt_em t_emp _empt empty next_e ext_em xt_emp t_empt _empty next_em ext_emp xt_empt t_empty next_emp ext_empt xt_empty next_empt ext_empty next_empty


but
b u t bu ut but
not_forever
n o t _ f o r e v e r no ot t_ _f fo or re ev ve er not ot_ t_f _fo for ore rev eve ver not_ ot_f t_fo _for fore orev reve ever not_f ot_fo t_for _fore forev oreve rever not_fo ot_for t_fore _forev foreve orever not_for ot_fore t_forev _foreve forever not_fore ot_forev t_foreve _forever not_forev ot_fo

# THIRD


In [25]:
import numpy as np

In [38]:
def main():
    p = int(input())
    powered = map(lambda x: int(x) ** p, raw_input().split())
    print(sum(powered) ** (1. / p))
    
main()

2
3 4
5.0


# FOURTH


In [49]:
def main():
    n = int(input())
    mapper = {'}':'{', ')':'(', ']':'['}
    for i in range(n):
        ans = True
        cbs = raw_input()
        checker = []
        for symbol in cbs:
            if symbol in {'[', '{', '('}:
                checker.append(symbol)
            else:
                if len(checker) == 0:
                    ans = False
                else:
                    if mapper[symbol] != checker.pop():
                        ans = False
        
        if len(checker) > 0 or ans == False:
            print('no')
        else:
            print('yes')
        
main()

2
[][]
yes
{
no


# FIFTH

In [85]:
data = map(int, raw_input().split())
print 

213
213


In [152]:
# import no_standard_sort


def slit(seq1, seq2):
    '''
    params:
    seq1: 
    seq2: 
    '''
    seq1 = list(seq1)
    seq2 = list(seq2)
    resultant_seq = []
    first_pointer, second_pointer = 0, 0
    while (first_pointer < len(seq1)) and second_pointer < (len(seq2)):
        if seq1[first_pointer] < seq2[second_pointer]:
            resultant_seq.append(seq1[first_pointer])
            first_pointer += 1
        else:
            resultant_seq.append(seq2[second_pointer])
            second_pointer += 1
    if first_pointer == len(seq1):
        resultant_seq += seq2[second_pointer:]
    else:
        resultant_seq += seq1[first_pointer:]
    return resultant_seq

def vizivaet_slit(seq):
    if(len(seq) == 1):
        return seq
    middle = len(seq) / 2
    return slit( vizivaet_slit(seq[:middle]), vizivaet_slit(seq[middle:]) )



def main():
    data = map(int, raw_input().split())
    if len(data) == 0:
        return
    result = vizivaet_slit(data)
    print(' '.join(map(str, result)))

main()

In [103]:
import scipy.stats as sps

In [134]:
datka = sps.poisson.rvs(3, size=6)
datka

array([1, 3, 3, 4, 6, 2])

In [135]:
sorted(datka)

[1, 2, 3, 3, 4, 6]

In [136]:
vizivaet_slit(datka)

array([19])

In [132]:
vizivaet_slit([1,3,3,7,2,2,8])

[1, 2, 2, 3, 3, 7, 8]

In [137]:
kdsak = [1,3,3,5]

In [138]:
irwiw = kdsak[:2]

In [139]:
irwiw[0]= 13337

In [167]:
datka = sps.poisson.rvs(3, size=1000000)
datka

array([2, 2, 1, ..., 1, 3, 4])

In [168]:
sr1 = sorted(datka)

In [169]:
sr2 = vizivaet_slit(datka)

In [170]:
sr2[:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [171]:
sr1[:10]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [172]:
sum([sr1[i] - sr2[i] for i in range(len(sr1))])

0

In [174]:
main()

12 120 12 -12  3 1  -2 1 9 48 213 921
-12 -2 1 1 3 9 12 12 48 120 213 921


# SIXTH

In [182]:
chr('a' + 1)

TypeError: cannot concatenate 'str' and 'int' objects

In [183]:
from collections import defaultdict

In [196]:
def main():
    dictionary = {chr(ord('a') + i):0 for i in range(26)}
    with open('dzPythonZen.txt', 'r+') as f:
        data = f.read()
        for symbol in data:
            other_sym = chr(ord(symbol) + 32)
            if symbol in dictionary:
                dictionary[symbol] += 1
            elif other_sym in dictionary:
                dictionary[other_sym] += 1
    for elem in sorted(dictionary.items(), key=lambda x: (-x[1], x[0])):
        if elem[1] != 0:
            print(elem[0] + ': ' + str(elem[1]))
        
main()

e: 92
t: 79
a: 53
i: 53
s: 46
o: 43
n: 42
l: 33
r: 33
h: 31
p: 22
b: 21
u: 21
c: 17
d: 17
y: 17
m: 16
f: 12
g: 11
x: 6
v: 5
w: 4
k: 2
z: 1


In [195]:
print(elem[0] + '')

q


# Seventh

In [212]:
n = int(input())
with open('dzPythonZen.txt', 'r') as f:
    asdwqe = f.readlines()
    for line in f.readlines():
        print line
    qwjri = map(lambda elem: elem.split(), asdwqe)

2


In [216]:
qwjri = map(lambda elem: elem.split(), asdwqe)

In [218]:
qwjri

[['The', 'Zen', 'of', 'Python,', 'by', 'Tim', 'Peters'],
 [],
 ['Beautiful', 'is', 'better', 'than', 'ugly.'],
 ['Explicit', 'is', 'better', 'than', 'implicit.'],
 ['Simple', 'is', 'better', 'than', 'complex.'],
 ['Complex', 'is', 'better', 'than', 'complicated.'],
 ['Flat', 'is', 'better', 'than', 'nested.'],
 ['Sparse', 'is', 'better', 'than', 'dense.'],
 ['Readability', 'counts.'],
 ['Special',
  'cases',
  "aren't",
  'special',
  'enough',
  'to',
  'break',
  'the',
  'rules.'],
 ['Although', 'practicality', 'beats', 'purity.'],
 ['Errors', 'should', 'never', 'pass', 'silently.'],
 ['Unless', 'explicitly', 'silenced.'],
 ['In',
  'the',
  'face',
  'of',
  'ambiguity,',
  'refuse',
  'the',
  'temptation',
  'to',
  'guess.'],
 ['There',
  'should',
  'be',
  'one--',
  'and',
  'preferably',
  'only',
  'one',
  '--obvious',
  'way',
  'to',
  'do',
  'it.'],
 ['Although',
  'that',
  'way',
  'may',
  'not',
  'be',
  'obvious',
  'at',
  'first',
  'unless',
  "you're",
  'Dut

In [222]:
from tqdm import tqdm

In [242]:
def main():
    n = int(input())
    with open('input.txt', 'r') as f:
        asdwqe = f.readlines()
    qwjri = map(lambda elem: elem.split(), asdwqe)
    
    answer = ''
    for line in tqdm(qwjri):
        if len(qwjri) == 0:
            answer += '\n'
            continue
        counter = 0
        curpos = 0
        while curpos < len(line):
            if counter + len(line[curpos]) > n:
                answer += '\n'
                counter = 0
                continue
            if counter == 0 and len(line[curpos]) > n:
                answer += line[curpos]
                answer += '\n'
                curpos += 1
                continue
            counter += len(line[curpos])
            answer += line[curpos]
            if counter != n:
                answer += ' '
                counter += 1
            curpos += 1
        if answer[-1] != '\n':
            answer += '\n'
            
    print answer
    
main()

2


IOError: [Errno 2] No such file or directory: 'input.txt'

In [207]:
splitted = data.split()

In [202]:
print(data)

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!



In [245]:
qwjri[0]

['The', 'Zen', 'of', 'Python,', 'by', 'Tim', 'Peters']

In [244]:
n = int(input())
with open('dzPythonZen.txt', 'r') as f:
    asdwqe = f.readlines()
qwjri = map(lambda elem: elem.split(), asdwqe)

answer = ''
for line in tqdm(qwjri):
    if len(line) == 0:
        answer += '\n'
        continue
    counter = 0
    curpos = 0
    while curpos < len(line):
        if counter == 0 and len(line[curpos]) > n:
            answer += line[curpos]
            answer += '\n'
            curpos += 1
            continue
        if counter + len(line[curpos]) > n:
            answer += '\n'
            counter = 0
            continue
        counter += len(line[curpos])
        answer += line[curpos]
        if counter != n:
            answer += ' '
            counter += 1
        curpos += 1
    if answer[-1] != '\n':
        answer += '\n'

print answer

2


  0%|          | 0/21 [00:00<?, ?it/s]


KeyboardInterrupt: 

In [250]:
line = ['The', 'Zen', 'of', 'Python,', 'by', 'Tim', 'Peters']

In [253]:
answer = ''
counter = 0
curpos = 0
while curpos < len(line):
    if counter == 0 and len(line[curpos]) > n:
        answer += line[curpos]
        answer += '\n'
        curpos += 1
        continue
    if counter + len(line[curpos]) > n:
        answer += '\n'
        counter = 0
        continue
    counter += len(line[curpos])
    answer += line[curpos]
    if counter != n:
        answer += ' '
        counter += 1
    curpos += 1

In [256]:
print answer

The
Zen
of
Python,
by
Tim
Peters



In [265]:
def slit(seq1, seq2):
    '''
    params:
    seq1:  LISTS, NOT NP.ARRAYS
    seq2: 
    '''
    resultant_seq = []
    first_pointer, second_pointer = 0, 0
    while (first_pointer < len(seq1)) and second_pointer < (len(seq2)):
        if seq1[first_pointer] < seq2[second_pointer]:
            resultant_seq.append(seq1[first_pointer])
            first_pointer += 1
        else:
            resultant_seq.append(seq2[second_pointer])
            second_pointer += 1
    if first_pointer == len(seq1):
        resultant_seq += seq2[second_pointer:]
    else:
        resultant_seq += seq1[first_pointer:]
    return resultant_seq

def vizivaet_slit(seq):
    if(len(seq) == 1):
        return seq
    middle = len(seq) / 2
    return slit( vizivaet_slit(seq[:middle]), vizivaet_slit(seq[middle:]) )



def main():
    data = map(int, raw_input().split())
    if len(data) == 0:
        return
    result = vizivaet_slit(data)
    print ' '.join(map(str, result)),

main()

213 4 41 12 
4 12 41 213


In [267]:
import sys

''